from __future__ import annotations
import math
import torch
from .config import CFG


def make_teacher_dataset(seed: int = 100, device: torch.device | str = "cpu"):
    """Deterministic synthetic classification dataset generated by a fixed teacher MLP.

    A synthetic teacher gives us a controlled, effectively noise-free benchmark where width,
    optimizer, LR schedule, and seed can be changed independently without download variance.
    """
    n = CFG.train_size + CFG.val_size
    g = torch.Generator(device="cpu").manual_seed(seed)
    x = torch.randn(n, CFG.input_dim, generator=g)
    a = torch.randn(CFG.input_dim, CFG.teacher_hidden, generator=g) / math.sqrt(CFG.input_dim)
    b = torch.randn(CFG.teacher_hidden, CFG.n_classes, generator=g) / math.sqrt(CFG.teacher_hidden)
    with torch.no_grad():
        logits = torch.relu(x @ a) @ b
        y = logits.argmax(dim=-1)
    x_train, y_train = x[:CFG.train_size], y[:CFG.train_size]
    x_val, y_val = x[CFG.train_size:], y[CFG.train_size:]
    return (
        x_train.to(device), y_train.to(device),
        x_val.to(device), y_val.to(device),
    )


def make_batch_indices(steps: int, batch_size: int | None = None, seed: int = 123):
    batch_size = batch_size or CFG.batch_size
    g = torch.Generator(device="cpu").manual_seed(seed)
    return [torch.randint(0, CFG.train_size, (batch_size,), generator=g) for _ in range(steps)]
